// <auto-generated />
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Mains",
                            Description = "Juicy Steak and Chunky Chips",
                            ImageUrl = "https://andrewmmango.blob.core.windows.net/mango/Steak.jpg",
                            Name = "Steak",
                            Price = 24.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Mains",
                            Description = "Bacon Double Cheese Burger Served with Fries or Chunky Chips",
                            ImageUrl = "https://andrewmmango.blob.core.windows.net/mango/BaconCheeseBurger.jpg",
                            Name = "Double Bacon Cheese Burger",
                            Price = 14.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Mains",
                            Description = "Taste of Italy",
                            ImageUrl = "https://andrewmmango.blob.core.windows.net/mango/lasagne.jpg",
                            Name = "Lasagne",
                            Price = 12.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Mains",
                            Description = "Traditional favourite",
                            ImageUrl = "https://andrewmmango.blob.core.windows.net/mango/CodChips.jpg",
                            Name = "Beer Battered Cod & Chips",
                            Price = 14.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
